name: TCS
on:
  repository_dispatch:
    types: tcs-order-create-api-extension
  push:
    branches:
      - main
    paths:
      - 'tcs-order-create-api-extension/**'
      - '.github/workflows/order-create-api-extension-ci-master.yml'
      - '*.json'
      - '*.yml'
      - '*.yaml'
env:
  FIREBASE_TOKEN: 1//03iCXhA8czIrICgYIARAAGAMSNwF-L9IrwSCW3HIsANYrnEv4pBe7gkJ381wcqE-Vo3LBJ1h340hRYYTi6YsI3c7UP5D5vmUvjaY
  PROJECT_ID: commerce-tools-b2b-services
  PROJECT_PATH: tcs-order-create-api-extension
  CT_AUTH_URL: ${{ secrets.CT_AUTH_URL }}
  CT_API_URL: ${{ secrets.CT_API_URL }}
  CT_PROJECT_KEY: ${{ secrets.CT_PROJECT_KEY }}
  CT_CLIENT_ID: ${{ secrets.CT_CLIENT_ID }}
  CT_CLIENT_SECRET: ${{ secrets.CT_CLIENT_SECRET }}
  CT_SCOPE: ${{ secrets.CT_SCOPE }} 
jobs:
  lint:
    name: Lint (node.js)
    runs-on: ubuntu-22.04
    environment: tcs-env
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd tcs-order-create-api-extension
          npm install --no-audit
      - name: Lint Node.js
        run: |
          cd tcs-order-create-api-extension
          npm run lint
      - name: Lint Markdown
        run: |
          cd tcs-order-create-api-extension
          npm run lint-md
  deploy:
    name: Deploy Firebase function
    needs: lint
    runs-on: ubuntu-22.04
    environment: tcs-env
    strategy:
      matrix:
        node-version: [10.x]       
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd tcs-order-create-api-extension
          npm install --production

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:tscOrderCreate
